#ifndef _INCLUDE_PGT_H_
#define _INCLUDE_PGT_H_

#define PAGE_SIZE 4096
#define STACK_BASE 0x40000000
#define TEXT_BASE 0x2000000000
#define ADDRESS_FROM_STACK(a) ((TEXT_BASE > a) && (a >= STACK_BASE))
#define PAGE_BELOW(a) ((a / PAGE_SIZE) * PAGE_SIZE)

#define PGT_VALID_MASK 0x1
#define PGT_INVALID_MASK 0x0
#define PGT_WRITABLE_MASK 0x2
#define PGT_USER_MASK 0x4
#define PGT_ADDRESS_MASK 0xFFFFFFFFFF000
#define PGT_HUGEPAGE_MASK 0x80

#define PGT_IS_VALID(p) (p & PGT_VALID_MASK)
#define PGT_IS_HUGEPAGE(p) (p & PGT_HUGEPAGE_MASK)
#define PGT_ADDRESS(p) (p & PGT_ADDRESS_MASK)
#define PGT_INVALIDATE(p) (p &= PGT_INVALID_MASK)

#define PGT_PML4_INDEX_MASK 0xFF8000000000
#define PGT_PML3_INDEX_MASK 0x7FC0000000
#define PGT_PML2_INDEX_MASK 0x3FE00000
#define PGT_PML1_INDEX_MASK 0x1FF000

#define PGT_PML4_INDEX(v) ((v & PGT_PML4_INDEX_MASK) >> 39)
#define PGT_PML3_INDEX(v) ((v & PGT_PML3_INDEX_MASK) >> 30)
#define PGT_PML2_INDEX(v) ((v & PGT_PML2_INDEX_MASK) >> 21)
#define PGT_PML1_INDEX(v) ((v & PGT_PML1_INDEX_MASK) >> 12)

#endif
